version: '3.7'
services:
    spark:
        image: apache-spark
        container_name: spark-master
        build: .
        user: root
        restart: always
        environment:
            - SPARK_MODE=master
            - SPARK_RPC_AUTHENTICATION_ENABLED=no
            - SPARK_RPC_ENCRYPTION_ENABLED=no
            - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
            - SPARK_SSL_ENABLED=no
        volumes:
            - ./:/workspace
        ports:
            - "8181:8080"
            - "7077:7077"

    spark-worker-1:
        image: apache-spark
        container_name: spark-woker-1
        user: root
        restart: always
        environment:
            - SPARK_MODE=worker
            - SPARK_MASTER_URL=spark://spark:7077
            - SPARK_WORKER_MEMORY=12G
            - SPARK_WORKER_CORES=4
            - SPARK_RPC_AUTHENTICATION_ENABLED=no
            - SPARK_RPC_ENCRYPTION_ENABLED=no
            - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
            - SPARK_SSL_ENABLED=no
        volumes:
            - ./:/workspace
